[workspace]
members = [
    "fri3d-runtime",
    "fri3d-emulator",
    "fri3d-wasm-api",
    "fri3d-app-dots",
]
default-members = [
    "fri3d-runtime",
    "fri3d-emulator",
    "fri3d-wasm-api",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"
